### ISSUE TITLE
Add Unit Testing Framework

### ISSUE THREAD

**Issue by gcaufield** [StasTserk/DndStuff#7]
Probably add the Rhino DLLs to a nuget on the application and use the built C# Testing framework.

Unless there is a strong desire for nunit

@StasTserk Opinions?

**Comment by StasTserk** [comment]
http://jimmykeen.net/2014/12/13/mocking-frameworks-comparison/
I do not know much.

**Comment by gcaufield** [comment]
Rhino and MSTest because why not
